# Caches the PowerShell script generated by slow init commands (e.g. `zoxide init`,
# `dsc completer`) so most shell startups can just read a file instead of spawning a
# process (each spawned process gets intercepted/scanned by EDR on locked-down
# machines, adding real latency). The cache is refreshed opportunistically via the
# PowerShell.OnIdle event (fires after the first prompt, best effort - if it never
# fires in a given session, the existing cache is simply reused next time, so
# correctness never depends on it firing) and is force-refreshed synchronously if the
# source executable is newer than the cache (e.g. after an upgrade).
function Invoke-CachedInit {
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$SourceCommand,
        [Parameter(Mandatory)][scriptblock]$Generate
    )

    $cacheDir = Join-Path $env:LOCALAPPDATA 'psprofile\cache'
    if (-not (Test-Path $cacheDir)) {
        New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
    }
    $cacheFile = Join-Path $cacheDir "$Name.ps1"

    $sourcePath = (Get-Command -Name $SourceCommand -ErrorAction SilentlyContinue).Source
    $stale = $true
    if (Test-Path $cacheFile) {
        $stale = $sourcePath -and ((Get-Item $sourcePath).LastWriteTimeUtc -gt (Get-Item $cacheFile).LastWriteTimeUtc)
    }

    if ($stale) {
        $script = & $Generate
        Set-Content -Path $cacheFile -Value $script
        Invoke-Expression $script
    }
    else {
        . $cacheFile
    }

    # Best-effort background refresh for next time. If OnIdle never fires this
    # session, the cache above is still correct (just possibly stale) - freshness
    # here is an optimization, not a correctness requirement.
    Register-EngineEvent -SourceIdentifier PowerShell.OnIdle -MaxTriggerCount 1 -MessageData @{
        CacheFile = $cacheFile
        Generate  = $Generate
    } -Action {
        $script = & $Event.MessageData.Generate
        Set-Content -Path $Event.MessageData.CacheFile -Value $script
    } | Out-Null
}
