$IsAdmin = & {
    if ($IsWindows) {
        $wid = [System.Security.Principal.WindowsIdentity]::GetCurrent()
        $prp = New-Object System.Security.Principal.WindowsPrincipal($wid)
        $adm = [System.Security.Principal.WindowsBuiltInRole]::Administrator
        $prp.IsInRole($adm)
    }
    elseif ($IsLinux) {
        (id) -like 'uid=0*'
    }
}

function Import-RequiredModule {
    param(
        [string[]]$Name,
        [switch]$AllowClobber
    )

    $Name | ForEach-Object {
        if (-not (Get-Module -Name $_ -ListAvailable)) {
            Install-Module -Name $_ -Scope CurrentUser -AllowClobber:$AllowClobber
        }
        Import-Module $_
    }
}

# Caches the PowerShell script generated by slow init commands (e.g. `zoxide init`,
# `dsc completer`) so most shell startups can just read a file instead of spawning a
# process (each spawned process gets intercepted/scanned by EDR on locked-down
# machines, adding real latency). The cache is refreshed opportunistically via the
# PowerShell.OnIdle event (fires after the first prompt, best effort - if it never
# fires in a given session, the existing cache is simply reused next time, so
# correctness never depends on it firing) and is force-refreshed synchronously if the
# source executable is newer than the cache (e.g. after an upgrade).
function Invoke-CachedInit {
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$SourceCommand,
        [Parameter(Mandatory)][scriptblock]$Generate
    )

    $cacheDir = Join-Path $env:LOCALAPPDATA 'psprofile\cache'
    if (-not (Test-Path $cacheDir)) {
        New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
    }
    $cacheFile = Join-Path $cacheDir "$Name.ps1"

    $sourcePath = (Get-Command -Name $SourceCommand -ErrorAction SilentlyContinue).Source
    $stale = $true
    if (Test-Path $cacheFile) {
        $stale = $sourcePath -and ((Get-Item $sourcePath).LastWriteTimeUtc -gt (Get-Item $cacheFile).LastWriteTimeUtc)
    }

    if ($stale) {
        $script = & $Generate
        Set-Content -Path $cacheFile -Value $script
        Invoke-Expression $script
    }
    else {
        . $cacheFile
    }

    # Best-effort background refresh for next time. If OnIdle never fires this
    # session, the cache above is still correct (just possibly stale) - freshness
    # here is an optimization, not a correctness requirement.
    Register-EngineEvent -SourceIdentifier PowerShell.OnIdle -MaxTriggerCount 1 -MessageData @{
        CacheFile = $cacheFile
        Generate  = $Generate
    } -Action {
        $script = & $Event.MessageData.Generate
        Set-Content -Path $Event.MessageData.CacheFile -Value $script
    } | Out-Null
}

# $PSScriptRoot (not $profile) so this still resolves when $PROFILE is a stub
# that dot-sources us from a different (e.g. OneDrive-redirected) location.
Set-Variable -Name ProfileDir -Value $PSScriptRoot
Set-Variable -Name ModuleDir -Value (Join-Path $ProfileDir 'Modules')

# On machines where the profile has been moved out of a redirected Documents
# folder, $DefaultModuleDir (where Install-Module -Scope CurrentUser writes)
# differs from $ModuleDir (the faster local copy); on unmigrated machines
# they're the same and this whole block is a no-op.
$DefaultModuleDir = Join-Path (Split-Path $PROFILE.CurrentUserAllHosts) 'Modules'
if ($DefaultModuleDir -ne $ModuleDir) {
    if ($env:PSModulePath -notlike "*$ModuleDir*") {
        $env:PSModulePath = "$ModuleDir$([System.IO.Path]::PathSeparator)$env:PSModulePath"
    }

    # Picks up modules installed manually via `Install-Module -Scope CurrentUser`,
    # which always writes to $DefaultModuleDir regardless of $env:PSModulePath.
    if (Test-Path $DefaultModuleDir) {
        $existingModules = if (Test-Path $ModuleDir) { (Get-ChildItem $ModuleDir -Directory).Name } else { @() }
        Get-ChildItem $DefaultModuleDir -Directory -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -notin $existingModules } |
            ForEach-Object {
                Write-Host -ForegroundColor Blue "Copying module '$($_.Name)' to local profile Modules folder..."
                Copy-Item $_.FullName (Join-Path $ModuleDir $_.Name) -Recurse -Force
            }
    }
}

# Dot-sourcing ~35 files costs several seconds (EDR scan-on-open overhead per
# file), so most are concatenated into one cached file, regenerated only when
# the source files change. Files that depend on $PSScriptRoot/$PSCommandPath
# resolving to their own location are excluded here and dot-sourced directly.
$script:UncombinableFunctionFiles = @(
    'ConvertTo-ASCIIArt.ps1'
    'Update-WinGet.ps1'
    'Use-PromptTheme.ps1'
)

$FunctionsCacheDir = Join-Path $env:LOCALAPPDATA 'psprofile\cache'
$FunctionsCacheFile = Join-Path $FunctionsCacheDir 'functions-combined.ps1'

$functionFolders = (Join-Path $PSScriptRoot 'Functions'), (Join-Path $PSScriptRoot "${env:COMPUTERNAME}\Functions") |
    Where-Object { Test-Path $_ }

$allFunctionFiles = $functionFolders | ForEach-Object { Get-ChildItem (Join-Path $_ '*.ps1') }
$combinableFiles = $allFunctionFiles | Where-Object { $_.Name -notin $script:UncombinableFunctionFiles }
$uncombinableFiles = $allFunctionFiles | Where-Object { $_.Name -in $script:UncombinableFunctionFiles }

# Signature (name + last-write-time) avoids reading file contents to detect changes.
$signature = ($combinableFiles | Sort-Object FullName | ForEach-Object { "$($_.FullName):$($_.LastWriteTimeUtc.Ticks)" }) -join '|'
$cachedSignature = if (Test-Path $FunctionsCacheFile) { (Get-Content $FunctionsCacheFile -TotalCount 1) -replace '^# SIGNATURE: ', '' } else { $null }

if ($signature -ne $cachedSignature) {
    if (-not (Test-Path $FunctionsCacheDir)) {
        New-Item -ItemType Directory -Path $FunctionsCacheDir -Force | Out-Null
    }
    $combined = New-Object System.Text.StringBuilder
    [void]$combined.AppendLine("# SIGNATURE: $signature")
    foreach ($file in $combinableFiles) {
        [void]$combined.AppendLine("# --- $($file.FullName) ---")
        [void]$combined.AppendLine((Get-Content $file.FullName -Raw))
    }
    Set-Content -Path $FunctionsCacheFile -Value $combined.ToString() -NoNewline
}

if ($combinableFiles) {
    . $FunctionsCacheFile
}
foreach ($file in $uncombinableFiles) {
    . $file.FullName
}

if ($IsWindows) {
    $script:ComputerName = $env:COMPUTERNAME
}
elseif ($IsLinux) {
    if (Get-Command hostname -ErrorAction SilentlyContinue) {
        $script:ComputerName = (hostname)
    }
    else {
        $script:ComputerName = Get-Content /etc/hostname
    }
}

# Import-Module Figlet costs ~1.2-1.4s (compiled .NET module bundling ~150 font
# .zip files). The rendered banner only changes with hostname/font, so the plain
# text is cached and colorized fresh each run based on $IsAdmin.
$FigletFont = 'big'
$FigletCacheDir = Join-Path $env:LOCALAPPDATA 'psprofile\cache'
$FigletCacheFile = Join-Path $FigletCacheDir "figlet-$script:ComputerName-$FigletFont.txt"

if (-not (Test-Path $FigletCacheFile) -or (Get-Item $FigletCacheFile).Length -eq 0) {
    if (-not (Test-Path $FigletCacheDir)) {
        New-Item -ItemType Directory -Path $FigletCacheDir -Force | Out-Null
    }
    # Write-Figlet writes directly to the host UI, so it can't be captured
    # in-process - a separate process with real stdout redirection is needed.
    $genScript = "Import-Module Figlet; [string](Write-Figlet '$script:ComputerName' -Font $FigletFont)"
    & pwsh -NoProfile -Command $genScript *> $FigletCacheFile
}

Get-Content $FigletCacheFile | ForEach-Object {
    Write-Host $_ -ForegroundColor ($IsAdmin ? 'Red' : 'Blue')
}

if (Get-Command -Name code -ErrorAction SilentlyContinue) {
    $env:EDITOR = 'code'
}
else {
    if ($IsWindows) {
        $env:EDITOR = 'notepad'
    }
}

if (Test-Path ~/bin) {
    Add-Path ~/bin
}

if (Test-Path $PSScriptRoot/scripts) {
    Add-Path $PSScriptRoot/scripts
}

if (Test-Path ~/.git_commands) {
    Add-Path ~/.git_commands
}

if ($IsWindows) {
    foreach ($dotfile in (Get-ChildItem -File -Path (Join-Path $PSScriptRoot 'dotfiles'))) {
        $destination = Join-Path ~ (Split-Path -Leaf $dotfile)
        if (-not (Test-Path $destination -PathType Leaf)) {
            if ($IsAdmin) {
                Write-Host -ForegroundColor Blue "Linking dotfile '$destination'..."
                New-Item -Path $destination -ItemType SymbolicLink -Value $dotfile | Out-Null
            }
            else {
                Write-Warning "Unable to create symlink for '$destination'. Open an elevated PowerShell to create the symlink."
            }
        }
    }
    foreach ($dotfolder in (Get-ChildItem -Directory -Path (Join-Path $PSScriptRoot 'dotfiles'))) {
        $destination = Join-Path ~ (Split-Path -Leaf $dotfolder)
        if (-not (Test-Path $destination -PathType Container)) {
            if ($IsAdmin) {
                Write-Host -ForegroundColor Blue "Linking dotfolder '$destination'..."
                New-Item -Path $destination -ItemType SymbolicLink -Value $dotfolder | Out-Null
            }
            else {
                Write-Warning "Unable to create symlink for folder '$destination'. Open an elevated PowerShell to create the symlink."
            }
        }
    }
}

# posh-git's import costs ~2.3s; we only use its git/tgit/gitk tab completion,
# not its prompt integration, so defer the import to first actual tab-completion
# use. Register-ArgumentCompleter replaces this stub with posh-git's own real
# completer once it imports, so this only runs once per session at most.
# To back out: replace this block with `Import-RequiredModule posh-git`.
Register-ArgumentCompleter -CommandName git, tgit, gitk, g -Native -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    if (-not (Get-Module posh-git)) {
        Import-Module posh-git
    }
    $padLength = $cursorPosition - $commandAst.Extent.StartOffset
    $textToComplete = $commandAst.ToString().PadRight($padLength, ' ').Substring(0, $padLength)
    Expand-GitCommand $textToComplete
}

# if (Get-Module PowerLocation -ListAvailable) {
#     Import-Module PowerLocation
#     Set-Alias -Name z -Value Set-PowerLocation
# }

. $PSScriptRoot/customprompt.ps1

. (Join-Path $PSScriptRoot psreadlinecfg.ps1)

#. (Join-Path $PSScriptRoot DynamicTitle.ps1)

if (Get-Command fzf -ErrorAction SilentlyContinue) {
    Import-RequiredModule PSFzf
    Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r' -PSReadlineChordSetLocation 'Ctrl+l'
    Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-FzfTabCompletion }
    $_fzf_bat_cmd = 'bat --color=always --line-range :100 {}'
    $_fzf_fd_all_cmd = 'fd -tf -td -tl {0}' -f $env:FD_OPTIONS
    $env:FZF_DEFAULT_OPTS = "--prompt '⯈ ' --height 50% --layout=reverse --border --color=dark --color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f --color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7"
    $env:FD_OPTIONS = '--hidden --follow'
    $env:FZF_DEFAULT_COMMAND = $_fzf_fd_all_cmd
    $env:FZF_CTRL_T_OPTS = "--preview `"$_fzf_bat_cmd`""
    $env:FZF_CTRL_T_COMMAND = $_fzf_fd_all_cmd

    Set-Alias -Name fe -Value Invoke-FuzzyEdit
    Set-Alias -Name fgs -Value Invoke-FuzzyGitStatus
    Set-Alias -Name fh -Value Invoke-FuzzyHistory
    Set-Alias -Name fkill -Value Invoke-FuzzyKillProcess
    Set-Alias -Name fcd -Value Invoke-FuzzySetLocation
}

if (Get-Command zoxide -ErrorAction SilentlyContinue) {
    # zoxide init spawns a process, which is EDR-intercepted (real latency), so the
    # output is cached to disk (see Invoke-CachedInit) instead of regenerated every
    # startup. To back out: replace with
    #   Invoke-Expression (& { (zoxide init powershell --cmd z --hook pwd | Out-String) })
    Invoke-CachedInit -Name 'zoxide-init' -SourceCommand zoxide -Generate {
        zoxide init powershell --cmd z --hook pwd | Out-String
    }
    Set-Alias -Name cd -Value z -Option AllScope
    Register-ArgumentCompleter -CommandName z -Native -ScriptBlock {
        param($stringMatch)
        $zquery = zoxide query -l $stringMatch
        $iquery = Get-ChildItem "$stringMatch*" -Directory -ErrorAction SilentlyContinue | ForEach-Object { $_.Name }
        @($zquery) + @($iquery) | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
    }
    $env:_ZO_FZF_OPTS = $env:FZF_DEFAULT_OPTS
}

if (Get-Command bat -ErrorAction SilentlyContinue) {
    $env:BAT_THEME = 'Nord'
    $env:BAT_STYLE = 'changes,header,numbers'
}

if (Get-Command claude -ErrorAction SilentlyContinue) {
    Set-Alias -Name cld -Value claude
    function cldy {
        claude --dangerously-skip-permissions $args
    }
}

if (Get-Command -Name dotnet -ErrorAction SilentlyContinue) {
    Write-Host -ForegroundColor Blue "Registering argument completer for 'dotnet'..."
    Register-ArgumentCompleter -Native -CommandName dotnet -ScriptBlock {
        param($commandName, $wordToComplete, $cursorPosition)
        dotnet complete --position $cursorPosition "$wordToComplete" | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
    }
}
else {
    Write-Information "Command 'dotnet' not found."
}

if (Get-Command -Name dsc -ErrorAction SilentlyContinue) {
    # dsc completer spawns a process, which is EDR-intercepted, so it's cached
    # to disk (see Invoke-CachedInit). To back out: replace with
    #   dsc completer powershell | Out-String | Invoke-Expression
    Write-Host -ForegroundColor Blue "Registering argument completer for 'dsc'..."
    Invoke-CachedInit -Name 'dsc-completer' -SourceCommand dsc -Generate {
        dsc completer powershell | Out-String
    }
}

if (Get-Command -Name winget -ErrorAction SilentlyContinue) {
    Write-Host -ForegroundColor Blue "Registering argument completer for 'winget'..."
    Register-ArgumentCompleter -Native -CommandName winget -ScriptBlock {
        param($wordToComplete, $commandAst, $cursorPosition)
        [Console]::InputEncoding = [Console]::OutputEncoding = $OutputEncoding = [System.Text.Utf8Encoding]::new()
        $Local:word = $wordToComplete.Replace('"', '""')
        $Local:ast = $commandAst.ToString().Replace('"', '""')
        winget complete --word="$Local:word" --commandline "$Local:ast" --position $cursorPosition | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
    }
}
else {
    Write-Information "Command 'winget' not found."
}

if (Get-Command -Name nuke -ErrorAction SilentlyContinue) {
    Write-Host -ForegroundColor Blue "Registering argument completer for 'nuke'..."
    Register-ArgumentCompleter -Native -CommandName nuke -ScriptBlock {
        param($commandName, $wordToComplete, $cursorPosition)
        nuke :complete "$wordToComplete" | ForEach-Object {
            if (-not $_.StartsWith('NUKE Global Tool')) {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        }
    }
}
else {
    Write-Information "Command 'nuke' not found."
}

if (Get-Command -Name npm -ErrorAction SilentlyContinue) {
    if ($env:PATH -notlike "*npm*") {
        $env:PATH += "; $(npm config get prefix)"
    }
}

# Hopefully temporary fix for "dotnet new" slowness (https://github.com/dotnet/templating/issues/2093)
#$env:DOTNET_NEW_LOCAL_SEARCH_FILE_ONLY = 1

@(Join-Path $PSScriptRoot "machine\${env:COMPUTERNAME}\$($MyInvocation.MyCommand.Name)") |
    Where-Object { Test-Path $_ } |
    ForEach-Object { . $_ }

Set-Alias -Name b -Value './build.ps1'

if ($IsLinux) {
    Set-Alias -Name ls -Value Get-ChildItem
}

if ((Test-Path '/.dockerenv') -and (Test-Path ~/.container/profile.ps1)) {
    . ~/.container/profile.ps1
}

if (Get-Command -Name flightplan -ErrorAction SilentlyContinue) {
    Set-Alias -Name fp -Value flightplan
}

# git status is fast (local); git fetch runs via Start-Process (not Start-Job,
# which requires a runspace and fails under ConstrainedLanguage mode on some
# locked-down machines) to avoid blocking startup.
Push-Location $ProfileDir
try {
    if (Get-Command -Name git -ErrorAction SilentlyContinue) {
        if (-not (git status | Select-String 'nothing to commit')) {
            Write-Warning 'Profile changes need to be committed and pushed'
        }
        else {
            try {
                $global:_ProfileGitFetchOutLog = [System.IO.Path]::GetTempFileName()
                $global:_ProfileGitFetchErrLog = [System.IO.Path]::GetTempFileName()
                $global:_ProfileGitFetchProcess = Start-Process -FilePath git -ArgumentList 'fetch' `
                    -WorkingDirectory $ProfileDir -WindowStyle Hidden -PassThru `
                    -RedirectStandardOutput $global:_ProfileGitFetchOutLog -RedirectStandardError $global:_ProfileGitFetchErrLog
            }
            catch {
                Remove-Item $global:_ProfileGitFetchOutLog, $global:_ProfileGitFetchErrLog -Force -ErrorAction SilentlyContinue
                $global:_ProfileGitFetchOutLog = $null
                $global:_ProfileGitFetchErrLog = $null
                $global:_ProfileGitFetchProcess = $null
            }
        }
    }
}
finally {
    Pop-Location
}

# NOTE: capture the ScriptBlock (not the FunctionInfo) - invoking a FunctionInfo
# via `&` re-resolves "prompt" by name, which after Set-Item below would recurse
# into the wrapper itself and blow the call stack.
$global:_origPromptFn = (Get-Item Function:\prompt).ScriptBlock
Set-Item Function:\prompt -Value {
    if ($global:_ProfileGitFetchProcess -and $global:_ProfileGitFetchProcess.HasExited) {
        try {
            Push-Location $ProfileDir
            $ahead = [int](git rev-list --count origin..HEAD 2>$null)
            $behind = [int](git rev-list --count HEAD..origin 2>$null)
            if ($ahead -gt 0) {
                Write-Warning 'Local profile changes need to be pushed'
            }
            elseif ($behind -gt 0) {
                Write-Warning 'Remote profile changes need to be merged'
            }
        }
        finally {
            Pop-Location
            Remove-Item $global:_ProfileGitFetchOutLog, $global:_ProfileGitFetchErrLog -Force -ErrorAction SilentlyContinue
            $global:_ProfileGitFetchProcess = $null
            $global:_ProfileGitFetchOutLog = $null
            $global:_ProfileGitFetchErrLog = $null
        }
    }
    & $global:_origPromptFn
}

if (Get-Command -Name copilot -ErrorAction SilentlyContinue) {
    function co { copilot --model claude-sonnet-4.5 @args }
    function coy { copilot --model claude-sonnet-4.5 --allow-all-tools @args }
    function coh { copilot --model claude-haiku-4.5 @args }
    function cohy { copilot --model claude-haiku-4.5 --allow-all-tools @args }
    function cog { copilot --model gpt-5 @args }
    function cogy { copilot --model gpt-5 --allow-all-tools @args }
}

function pd { Set-Location $ProfileDir }
function ep { code $ProfileDir }