#!/usr/bin/env bash
#
# This script creates a new feature branch.
#

# Use git-sh-setup: https://www.kernel.org/pub/software/scm/git/docs/git-sh-setup.html
OPTIONS_STUCKLONG=t
OPTIONS_KEEPDASHDASH=
OPTIONS_SPEC="\
git new-feature [options] <name>

Creates a new feature branch. The feature branch prefix defaults to 'feature/'
but can be set in the 'new-branch.feature.prefix' configuration item.

If '--parent' isn't specified the remote's default branch is implied.
--
p,parent=<parent>   the parent branch to use
"

SUBDIRECTORY_OK="yes" . "$(git --exec-path)/git-sh-setup"
. "$(dirname -- "$(readlink -f "$BASH_SOURCE")")/shared"

parent=
while test $# != 0; do
    case "$1" in
    --parent=*) parent=$(get_value "$1") ;;
    --) shift; break ;;
    esac
    shift
done

ARG_SPEC=('name')
parse_args "$@"

branch_prefix=$(git config --get new-branch.feature.prefix)
branch_prefix=${branch_prefix:-feature}

args=("$branch_prefix/$name")
if [ -n "$parent" ]; then
    args+=("--parent" "$parent")
fi
git new-branch ${args[*]}
