#!/usr/bin/env bash
#
# This script continues an in progress cherry-pick, rebase, merge or revert.
#

# Use git-sh-setup: https://www.kernel.org/pub/software/scm/git/docs/git-sh-setup.html
OPTIONS_STUCKLONG=t
OPTIONS_KEEPDASHDASH=
OPTIONS_SPEC="\
git abort

Continues an in progress cherry-pick, rebase, merge or revert.
--
"

SUBDIRECTORY_OK="yes" . "$(git --exec-path)/git-sh-setup"

require_work_tree

gitdir="$(git rev-parse --git-dir)" || die "Not in a Git working directory"
opfound=
fcnt=
for i in cherry-pick merge rebase revert; do
    f=${i^^}
    f=${f/-/_}
    test -f "${gitdir}/${f}_HEAD" && fcnt=1$fcnt && opfound=$i
done

if [ "${fcnt}" != 1 ]; then
    echo "I don't know what to abort" >&2
    exit 1
fi

git "${opfound}" --continue
