#!/usr/bin/env bash
#
# This script outputs the "default" branch of the repo.
#

# Use git-sh-setup: https://www.kernel.org/pub/software/scm/git/docs/git-sh-setup.html
OPTIONS_STUCKLONG=t
OPTIONS_KEEPDASHDASH=
OPTIONS_SPEC="\
git default-branch [options]
--
r,remote!=<remote>  the remote to get the default branch of; defaults to the result of 'git remote show'
"

SUBDIRECTORY_OK="yes" . "$(git --exec-path)/git-sh-setup"
. "$(dirname -- "$(readlink -f "$BASH_SOURCE")")/shared"

while [ "$#" != 0 ]; do
    case "$1" in
    --) shift; break ;;
    --remote=*) remote_name=$(get_value "$1") ;;
    esac
    shift
done

[ ! "$remote_name" ] && remote_name=$(git remote show)
[ ! "$remote_name" ] && die "No remote found"

git symbolic-ref -q "refs/remotes/$remote_name/HEAD" | sed "s@^refs/remotes/$remote_name/@@"
