#!/usr/bin/env bash
#
# This script creates a new hotfix branch.
#

# Use git-sh-setup: https://www.kernel.org/pub/software/scm/git/docs/git-sh-setup.html
OPTIONS_STUCKLONG=t
OPTIONS_KEEPDASHDASH=
OPTIONS_SPEC="\
git new-branch [options] <name>

Creates a new branch.

If '--parent' isn't specified the remote's default branch is implied.
--
p,parent=<parent> the parent branch to use
"

SUBDIRECTORY_OK="yes" . "$(git --exec-path)/git-sh-setup"
. "$(dirname -- "$(readlink -f "$BASH_SOURCE")")/shared"

parent=
while [ "$#" != 0 ]; do
    case "$1" in
    --parent=*) parent=$(get_value "$1") ;;
    --) shift; break ;;
    esac
    shift
done

ARG_SPEC=('name')
parse_args "$@"

require_branch_does_not_exist "$name"
require_clean_work_tree

if [ -z "$parent" ]; then
    parent=$(git default-branch)
fi

cur=$(get_current_branch)
if [ "$cur" != "$parent" ]; then
    remote=$(get_remote_for_branch "$cur")
    if [ -n "$remote" ]; then
        git done
        if [ "$(get_current_branch)" != "$parent" ]; then
            git switch "$parent"
        fi
    else
        git switch "$parent"
    fi
fi

git pull
git switch -c "$1"
