#!/usr/bin/env bash
#
# This script creates a new hotfix branch.
#

# Use git-sh-setup: https://www.kernel.org/pub/software/scm/git/docs/git-sh-setup.html
OPTIONS_STUCKLONG=t
OPTIONS_KEEPDASHDASH=
OPTIONS_SPEC="\
git new-branch [options] <name>

Creates a new branch.

If '--parent' isn't specified the remote's default branch is implied.
--
p,parent=<parent> the parent branch to use
"

SUBDIRECTORY_OK="yes" . "$(git --exec-path)/git-sh-setup"

die_with_usage() {
    printf >&2 '%s\n\n' "$*"
    usage
    exit 1
}

function get-value {
    IFS='=' read -ra parts <<<"$1"
    echo ${parts[1]}
}

parent=
while test $# != 0; do
    case "$1" in
    --parent=*) parent=$(get-value "$1") ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

if [ $# -eq 0 ]; then
    die_with_usage "Missing required branch name argument."
fi

if [ $# -gt 1 ]; then
    die_with_usage "Too many arguments."
fi

gitdir="$(git rev-parse --git-dir)" || die "Not in a Git working directory"

if [[ -n $(git status --porcelain) ]]; then
    die 'Uncommitted changes detected. Commit or stash your changes and try again.'
fi

if [ -z "$parent" ]; then
    remote=$(git remote show)
    parent="$(git remote show $remote | grep 'HEAD branch' | cut -d' ' -f5)"
fi

git checkout "$parent"
git pull
git checkout -b "$1"
