#!/usr/bin/env bash
#
# This script creates a new feature branch.
#

# Use git-sh-setup: https://www.kernel.org/pub/software/scm/git/docs/git-sh-setup.html
OPTIONS_STUCKLONG=t
OPTIONS_KEEPDASHDASH=
OPTIONS_SPEC="\
git new-feature [options] <name>

Creates a new feature branch. The feature branch prefix defaults to 'feature/'
but can be set in the 'new-branch.feature.prefix' configuration item.

If '--parent' isn't specified the remote's default branch is implied.
--
p,parent=<parent>   the parent branch to use
"

SUBDIRECTORY_OK="yes" . "$(git --exec-path)/git-sh-setup"

function get-value {
    IFS='=' read -ra parts <<<"$1"
    echo ${parts[1]}
}

parent=
while test $# != 0; do
    case "$1" in
    --parent=*) parent=$(get-value "$1") ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

if [[ -n $(git status --porcelain) ]]; then
    die 'Uncommitted changes detected. Commit or stash your changes and try again.'
fi

branch_prefix=$(git config --get new-branch.feature.prefix)
branch_prefix=${branch_prefix:-feature}

args=("$branch_prefix/$1")
if [ -n "$parent" ]; then
    args+=("--parent" "$parent")
fi
git new-branch ${args[*]}
